### ISSUE TITLE
Ansible jinja2 template 'wrong directory/missing step in the lab'

### ISSUE THREAD

**Issue by 5Q1VM5bgef** [het-tanis/prolug-labs#8]
The starting location of template.j2 should be changed to /root/template.j2 as the instructions say.
The line copying it should be removed.

Or the lab should have an additional step creating this file (template.j2) at /root/template.j2.

The lab is `07-Ansible-Playbook-Jinja-Templates`

![image](https://user-images.githubusercontent.com/111528540/232896725-a5eb30f8-3d27-4533-b1b0-759e9b5a291b.png)

**Comment by het-tanis** [comment]
I agree. I didn't discuss jinja templating in there. I'll make a step in the lab and inform them that file is just in case they can't find what they want to stamp on their own. Good looking out.

**Comment by 5Q1VM5bgef** [comment]
Same thing in the lab next to it `08-Ansible-Playbook-Jinja-Reporting`
In this one, jinja template file is not mentioned in instructions, nor in solution.

![image](https://user-images.githubusercontent.com/111528540/232920519-c46b7e64-4d6b-4ae7-b77a-5ff09ed252de.png)

**Comment by het-tanis** [comment]
Fixed both with last commit.
